name: "auto_gen_bind_pr"
description: "bindコードを生成するためのCIアクションをしてPRを送る"
inputs:
  triple:
    description: "cargo build target"
    required: true
  additional_features:
    description: "additional features"
    required: false
runs:
  using: "composite"
  steps:
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
      id: extract_branch
    - name: Install cross compiler for aarch64
      if: inputs.triple == 'aarch64-unknown-linux-gnu'
      shell: bash
      run: |
        sudo apt update
        sudo apt install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
    - uses: nttld/setup-ndk@v1
      if: endsWith(inputs.triple, '-linux-android')
      with:
        ndk-version: r25b
    - name: Set path for android
      if: endsWith(inputs.triple, '-linux-android')
      shell: bash
      run: |
        echo "$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin" >> "$GITHUB_PATH"
        UNDERSCORED_TRIPLE=$(sed 's/-/_/g' <<< "${{ inputs.triple }}")
        echo "AR_$UNDERSCORED_TRIPLE=llvm-ar" >> "$GITHUB_ENV"
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: install triple
      run: rustup target add ${{ inputs.triple }}
      shell: bash
    - uses: Swatinem/rust-cache@v2
      with:
        # cargoのキャシュが原因でテストが失敗してることが考えられる場合はバージョン部分を変更する
        key: "v1-cargo-test-cache-${{ inputs.triple }}"
    - name: gen bind
      run: RUST_BACKTRACE=1 cargo build -p onnxruntime-sys --target ${{ inputs.triple }} --features generate-bindings,${{ inputs.additional_features }} && git add --all
      shell: bash
    - name: create_pr
      id: cpr
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: Automated generate bindings for ${{ inputs.triple }}
        branch: ${{ steps.extract_branch.outputs.branch }}_auto_gen_bindings_${{ inputs.triple }}_${{ inputs.additional_features }}
        delete-branch: true
        title: Automated generate bindings for ${{ inputs.triple }} ${{ inputs.additional_features }}
        body: |
          Automated generate bindings for ${{ inputs.triple }} ${{ inputs.additional_features }}
